### ISSUE TITLE
Error Adding to Cart

### ISSUE THREAD

**Issue by TonyTheTech** [TeamUbersmith/order-forms#2]
When I click on "Add to Cart" I get the following errors on the next page:
###### ### 1st Error: Very top of the page towards the right side

Notice (8): Undefined variable: navigation_summary [APP/View/Layouts/default.ctp, line 31]
###### ### 2nd Error: Right below the "home" navigation link.

Database Error
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

SQL Query: SHOW TABLES FROM

Notice: If you want to customize this error message, create app/View/Errors/pdo_error.ctp
###### 

This is from the log file the page creates:

2014-02-25 07:05:15 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
#0 /var/www/order.mysite.com/www/lib/Cake/Model/Datasource/DboSource.php(459): PDOStatement->execute(Array)
#1 /var/www/order.mysite.com/www/lib/Cake/Model/Datasource/Database/Mysql.php(183): DboSource->_execute('SHOW TABLES FRO...')
#2 /var/www/order.mysite.com/www/lib/Cake/Model/Model.php(1101): Mysql->listSources()
#3 /var/www/order.mysite.com/www/lib/Cake/Model/Model.php(3191): Model->setSource('carts')
#4 /var/www/order.mysite.com/www/lib/Cake/Model/Model.php(1305): Model->getDataSource()
#5 /var/www/order.mysite.com/www/lib/Cake/Model/Model.php(1478): Model->schema()
#6 /var/www/order.mysite.com/www/app/Controller/ConfiguratorController.php(1084): Model->create()
#7 /var/www/order.mysite.com/www/app/Controller/ConfiguratorController.php(84): ConfiguratorController->step_2()
#8 [internal function]: ConfiguratorController->configure('2', '72')
#9 /var/www/order.mysite.com/www/lib/Cake/Controller/Controller.php(485): ReflectionMethod->invokeArgs(Object(ConfiguratorController), Array)
#10 /var/www/order.mysite.com/www/lib/Cake/Routing/Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/order.mysite.com/www/lib/Cake/Routing/Dispatcher.php(161): Dispatcher->_invoke(Object(ConfiguratorController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/order.mysite.com/www/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by TonyTheTech** [comment]
Is there a way in ubersmith to grab the mysql+php version in case you need that?

**Comment by ubersmith** [comment]
## There aren't currently any features within Ubersmith that would report the php or mysql versions.  That information would need to be attained directly from the server it is installed on.

-boo van alstyne
ubersmith vp support

---- Original message ----

> Is there a way in ubersmith to grab the mysql+php version in case you
> need that?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TeamUbersmith/order-forms/issues/2#issuecomment-36401130

To view this ticket online, log in to https://billing.ubersmith.com/ticket.php?ticket_id=307131
